[20기 양미화] Mission 2 회원가입 엔드포인트 # 2
wecode-bootcamp-korea/20-Westagram-backend pull request #15
Opened 2021-05-01 05:32 UTC by hwaya2828

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 생성한 users app의 models.py & views.py & urls.py 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- httpie로 데이터 들어가는건 확인했는데 너무 안좋은 코드 같아서 과제 마무리되는대로 전체적으로 다시 해보려고 생각중입니다 ^,ㅠ
- 고칠 때 try except으로 에러랑 성공 깔끔하게 정리해볼게용!
- ...지금 고쳐야될까요? ㅋㅋㅋㅋㅋ

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-02 07:03 UTC, Kang-kyunghun requested changes

2021-05-02 07:03 UTC, Kang-kyunghun commented on students/mihwa-yang/users/views.py
> +
공백은 1칸으로 해주세요. PEP8에서는 2칸을 권장하지만 위코드에서는 1칸으로 통일하겠습니다.

2021-05-02 07:03 UTC, Kang-kyunghun commented on students/mihwa-yang/users/views.py
> +
공백 제거해 주세요.

2021-05-02 07:03 UTC, Kang-kyunghun commented on students/mihwa-yang/users/views.py
> +                return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)
Unique에 따른 에러 처리인가요?

2021-05-02 07:03 UTC, Kang-kyunghun commented on students/mihwa-yang/users/views.py
> +                    phone    = data.get('phone')
data.get에서 .get을 사용한 이유를 설명해 주세요~

2021-05-02 07:03 UTC, Kang-kyunghun commented on students/mihwa-yang/users/views.py
> +            return JsonResponse({"MESSAGE": "EMAIL FORM ERROR"}, status=400)
만약에 위의 if문이 실행되면 return이 되면서 함수가 끝날 것 같은데, elif를 굳이 사용해야 할까요? 한 번 생각해 보세요~

2021-05-02 07:03 UTC, Kang-kyunghun commented on students/mihwa-yang/users/views.py
> +        elif len(data['password']) < 8:
비밀번호 길이에 대한 유효성 검사를 위해 8을 입력 했는데, 만약 기획이 바뀌어서 10자리로 늘린다면, 그런데 이 부분이 사용된 곳이 많다면, 전부 찾아서 고쳐야 겠죠? 그래서 이러한 부분은 상수로 처리하는 것이 좋습니다~!!

2021-05-02 07:03 UTC, Kang-kyunghun commented on students/mihwa-yang/users/urls.py
> +    path('', SignUpView.as_view()),
signup을 확실히 의미하는 url 주소로 바꾸면 좋을 것 같습니다.

2021-05-02 07:10 UTC, Kang-kyunghun commented
PR template에서 수정 사항 상세도 같이 기록해 주세요.

2021-05-02 07:33 UTC, Kang-kyunghun commented on students/mihwa-yang/users/models.py
> +
회원관리 측면에서 회원이 등록된 시점과 정보가 수정된 시점을 기록하는 것이 좋습니다.
장고에서 지원 해주는 시간 기록 필드를 추가해 주세요.

2021-05-02 10:34 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +
넵! 수정했습니다 👍

2021-05-02 10:35 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +
넵! 수정했습니다 👍

2021-05-02 10:35 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +                return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)
넵! 중복 에러 처리입니다 😊

2021-05-02 10:38 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +                    phone    = data.get('phone')
data['']로 가지고 오니 모델링에서 nickname과 phone에 null값을 줬음에도 키값이 없을 때 에러가 나서, 필수키값(email과 password)만 입력해도 post가 정상적으로 response될 수 있도록 .get('')을 사용했습니다 😊

2021-05-02 10:39 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +            return JsonResponse({"MESSAGE": "EMAIL FORM ERROR"}, status=400)
넵! 조건문의 연관성을 생각해봤을 때 if - elif 관계를 적용하지 않아도 될 것 같습니다! if로 수정했습니다 👍

2021-05-02 10:43 UTC, hwaya2828 commented on students/mihwa-yang/users/urls.py
> +    path('', SignUpView.as_view()),
넵! 수정했습니다 👍

2021-05-02 11:01 UTC, hwaya2828 commented on students/mihwa-yang/users/models.py
> +
넵! 수정했습니다 👍

2021-05-02 11:07 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +        elif len(data['password']) < 8:
넵! 수정했습니다 👍

2021-05-03 02:38 UTC, Kang-kyunghun commented on students/mihwa-yang/users/views.py
> +                    phone    = data.get('phone')
명확한 이유 너무 좋습니다~~!!

2021-05-03 02:43 UTC, Kang-kyunghun requested changes

2021-05-03 02:43 UTC, Kang-kyunghun commented on students/mihwa-yang/users/views.py
> +        if password_length < 8:
```suggestion
        PASSWORD_LENGTH = 8
        if data['password'] < PASSWORD_LENGTH:
```
제가 의도한 상수화는 위와 같았습니다~

2021-05-03 03:53 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +        if password_length < 8:
아!!!!!!! 하면서도 긴가민가 했었는데..! 
경훈님 감사합니다 수정했습니다 👍

2021-05-03 03:53 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +                    phone    = data.get('phone')
우와~ 감사합니다! 😊

2021-05-03 07:41 UTC, Kang-kyunghun requested changes

2021-05-03 07:41 UTC, Kang-kyunghun commented on students/mihwa-yang/users/views.py
> +            except IntegrityError:
해당 예외 처리는 DB에 문제가 있을 때 발생하는 예외 처리입니다. 그래서 당연히 unique에 대해서도 예외 처리가 되지만, 또 다른 DB 문제가 발생할 겨우 디버딩이 힘들어 질 것 같습니다. 그래서 create 이전에 존재 유무를 확인하는 것이 좋을 것 같습니다.

2021-05-03 08:14 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +            except IntegrityError:
넵! 수정했습니다 👍

2021-05-03 09:14 UTC, Kang-kyunghun requested changes

2021-05-03 09:14 UTC, Kang-kyunghun commented on students/mihwa-yang/users/views.py
> +            return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)
```suggestion
        if User.objects.filter(email=data.get('email')).exists()  \
            or User.objects.filter(nickname=data.get('nickname')).exists() \
            or User.objects.filter(phone=data.get('phone')).exists():
            return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)
```
.exits()의 반환값이 이미 boolean이기 때문에 == 으로 True/False을 구분하지 않으셔도 됩니다.(이렇게 짜는 것이 파이썬스럽다 라고 할 수 있습니다.)

2021-05-03 09:14 UTC, Kang-kyunghun commented on students/mihwa-yang/users/views.py
> +        else:
로직상 else가 필요할까요? elif랑 같은 맥락입니다.

2021-05-03 11:06 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +            return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)
넵! 수정했습니다 👍

2021-05-03 11:06 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +        else:
넵! 수정했습니다 👍

2021-05-03 13:19 UTC, Kang-kyunghun requested changes

2021-05-03 13:19 UTC, Kang-kyunghun commented on students/mihwa-yang/users/views.py
> +                        return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)
가독성이 너무 안 좋습니다. 일단 이 부분에 대해서 저랑 오전에 구두로 한 번 이야기 해봐요~

2021-05-04 00:33 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +                        return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)
if User.objects.filter(email=data.get('email')).exists():
            return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)

        if User.objects.filter(nickname=data.get('nickname')).exists() \
            and User.objects.filter(nickname=data.get('nickname') != None)
            return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)

        if User.objects.filter(phone=data.get('phone')).exists() \
            and User.objects.filter(phone=data.get('phone') != None):
            return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)

2021-05-04 00:34 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +                        return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)
그럼 혹시 이렇게 다 따로 if 처리하면 어떨까용?

2021-05-04 01:19 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +                        return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)
if User.objects.filter(email=data.get('email')).exists():
            return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)

        if User.objects.filter(nickname=data.get('nickname')).exists() and User.objects.filter(nickname=data.get('nickname') != None):
            return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)

        if User.objects.filter(phone=data.get('phone')).exists() and User.objects.filter(phone=data.get('phone') != None):
            return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)

2021-05-04 01:19 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +                        return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)
혹시 이렇게 if문으로 하나씩 따로 주면 어떨까용?

2021-05-04 01:54 UTC, hwaya2828 commented on students/mihwa-yang/users/views.py
> +                        return JsonResponse({"MESSAGE": "ALREADY EXIT ERROR"}, status=400)
수정했습니다 👍
models에서 unique 제거 했는데도 null값 안걸러주니까 중복 에러 떠서 'is not None' 부분은 그대로 사용했습니당

2021-05-04 02:03 UTC, Kang-kyunghun commented
고생하셨습니다.

2021-05-04 02:04 UTC, merged