[20기 정운산] [Mission 2] 회원가입 엔드포인트
wecode-bootcamp-korea/20-Westagram-backend pull request #16
Opened 2021-05-01 06:07 UTC by Action2theFuture

> ✔️ 모든 서비스는 회원가입에서 시작됩니다. 사용자를 우리 서비스의 회원으로 등록하는 과정에 대해 진행하겠습니다.
> ✔️ 구현하셔야 하는 내용 이후에는, 해당 코드를 효율적으로 작성하기 위한 정보들이 나열되어 있습니다.
> ✔️ 코드리뷰시 중점적으로 다루는 내용이니 꼭 숙지하시기 바랍니다.

# 01. user app을 생성해주세요.

앱 이름에서 그 용도를 유추할 수 있어야 합니다. 사용자와 관련된 기능을 구현할 앱이므로, `users` 또는 `accounts`등의 이름으로 앱을 생성해주세요.
# 02. 사용자 테이블을 생성해주세요.
- `models.py`에 사용자를 관리할 클래스를 생성합니다.
- 클래스 이름은 📍[파이썬 코딩 컨벤션](https://www.notion.so/wecode/Wecode-Python-Coding-Convention-0bd47a6018634454b9ee1e27984cb83a)을 따라주세요.
- 아래 규칙들을 지켜 생성해주세요. 관련 PR & Review를 참고하시면 더 좋은 코드를 만드실 수 있습니다.

### ✅  클래스 및 함수, 변수 이름 설정
> 클래스 이름, 함수 이름을 포함하여 모든 변수 이름을 짓는데에는 규칙이 있습니다. 위 `파이썬 코딩 컨벤션`을 따라주세요.

- **📍 관련 PR & Review**

  <details>
  <summary>모든 변수의 이름은 명확하게</summary>

  ![image](https://user-images.githubusercontent.com/42701133/100612016-9b8edd00-3355-11eb-84fc-fd28ca9553b8.png)
  </details>
 
  <details>
  <summary>table 이름은 class 이름과 동일하게, 복수형으로</summary>

  ![image](https://user-images.githubusercontent.com/42701133/100611338-89f90580-3354-11eb-84ac-ace833f7a12c.png)
  
  ![image](https://user-images.githubusercontent.com/42701133/100634730-01d62880-3373-11eb-850e-c9f3a5734ae4.png)

  </details>

### ✅  코드 간격 정렬 
> 코드는 크게 `=`, `:`, `import` 를 기준으로 같은 간격으로 정렬해줍니다. 복잡한 코드를 좀 더 읽기 쉽게 해줍니다.

- **📍 관련 PR & Review**

  <details> 
  <summary>import 기준으로 코드 정렬</summary>

  ![image](https://user-images.githubusercontent.com/42701133/100611240-633acf00-3354-11eb-917f-ed2655a2dea1.png)
  </details>

  <details>
  <summary> '=' 또는 ':' 기준으로 코드 정렬</summary>

  ![image](https://user-images.githubusercontent.com/42701133/100630632-254aa480-336e-11eb-8994-e24cdf42f2bd.png)
  ![image](https://user-images.githubusercontent.com/42701133/100612249-06401880-3356-11eb-8e09-d2b981823104.png)
  </details>

# 03. 회원가입 뷰를 작성해주세요.

- 생성한 사용자 클래스를 불러옵니다. 한 번에 모든 클래스를 import 해서는 안됩니다. 내가 사용할 클래스를 정확히 지칭해주세요
- 인스타그램에 회원가입 할 때에는 사용자 계정으로 **이메일**을 필수로 필요합니다.
- 인스타그램에 회원가입 할 때에는 **비밀번호**도 필수로 필요합니다.
- 회원가입 할 때 핸드폰 번호와 닉네임도 추가로 저장합니다.
- 이메일이나 패스워드 키가 전달되지 않았을 시, {"message": "KEY_ERROR"}, status code 400 을 반환합니다.
- 회원가입시 이메일을 사용할 경우, 이메일에는 `@`와 `.`이 필수로 포함되어야 합니다. 해당 조건이 만족되지 않을 시 적절한 에러를 반환해주세요. 이 과정을 email validation이라고 합니다.
- 회원가입시 비밀번호는 8자리 이상이어야만 합니다. 해당 조건이 만족되지 않을 시, 적절한 에러를 반환해주세요. 이 과정을 password validation이라고 합니다.
- 회원가입시 서로 다른 사람이 같은 전화번호나 사용자 이름, 이메일을 사용하지 않으므로 기존에 존재하는 자료와 중복되어서는 안됩니다. 적절한 에러를 반환해주세요.
- 회원가입이 성공하면 {"message": "SUCCESS"}, status code 201을 반환합니다.
- _[추가 구현 사항]_ -> email validation 또는 password validation 과정에서 [정규식](https://regexr.com/)을 사용해보세요.

### ✅  모듈을 import 하는 순서 및 규칙
> 모듈을 import 하는 데에도 순서가 있습니다.
> 1. python 모듈,
> 2. django 모듈,
> 3.  내가 만든 클래스
>
>  순서로 import 해주시고, 각 1,2,3번 사이에는 빈 줄을 삽입해주세요.

- **📍 관련 PR & Review**
  <details>
  <summary>import 순서와 간격이 맞지 않은 경우 </summary>
  
  ![image](https://user-images.githubusercontent.com/42701133/100632239-f46b6f00-336f-11eb-8be0-3e44b37aa1d6.png)
  </details>

  <details>
  <summary>부적절한 import *</summary>

  ![image](https://user-images.githubusercontent.com/42701133/100632654-7065b700-3370-11eb-8ea2-1a2a301f905f.png)
  </details>

### ✅ Pythonic Coding
> 파이썬은 `말하듯이 코딩하는` 스타일을 지향하고 있습니다. 아직 파이썬에 익숙하지 않기 때문에, 몇가지 스타일만 예시로 체험하도록 하겠습니다.

- **📍 관련 PR & Review**

  <details>
  <summary>Truthy / Falsy 한 값은 그 자체로 평가함</summary>
  
  ![image](https://user-images.githubusercontent.com/42701133/100633812-e1599e80-3371-11eb-83e8-6fcf996578a8.png)
  
  ![image](https://user-images.githubusercontent.com/42701133/100635486-eddef680-3373-11eb-959c-9e0c6168d2d8.png)

  🛎 `Truthy / Falsy` 에 대해 공부해보세요
  </details>

  <details>
  <summary>불필요한 else는 사용하지 않음</summary>
  
  ![image](https://user-images.githubusercontent.com/42701133/100634952-4366d380-3373-11eb-8126-81f3cb5ea7a4.png)
  </details>

### ✅ Error Handling
> 언제나 정상적으로 작동하는 코드만 있다면 얼마나 행복할까요? 하지만 `정상적인` 코드는 언제나 엄격한 에러 핸들링에서 나온답니다. 일어날 수 있는 버그를 최대한 많이 핸들링하는 습관을 들이셔야 합니다.

- **📍 관련 PR & Review**

  <details>
  <summary>에러 메세지도 통일해주기</summary>
  코드는 어제나 통일감과 가독성이 중요합니다. 에러메세지 또한 그 양식을 통일하여, 코드를 읽는 이로 하여금 이해가 쉽도록 작성하여야 합니다.

  ![image](https://user-images.githubusercontent.com/42701133/100635247-a48ea700-3373-11eb-829f-ad4bc3df65c7.png)
  </details>

  <details>
  <summary>Error catching의 좋은 예 - 에러 핸들링은 자세하게</summary>
    적절한 에러 핸들링은 어떤 오류가 발생하였는지 상세히 알려주기 때문에 디버깅을 쉽게 만들어줍니다. 따라서 발생할 수 있는 여러 상황에 대해 에러 핸들리을 해주는 것이 좋습니다. 회원가입시 발생할 수 있는 오류 사항에는 다음과 같은 경우가 있습니다.
  
  - 이메일이나 비밀번호라는 데이터가 들어오지 않았을 때
  - 계정(이메일, 아이디)의 형식이 맞지 않을 때
  - 비밀번호의 형식이 맞지 않을 때
  - 이미 가입한 유저가 회원가입을 시도할 때

  ![image](https://user-images.githubusercontent.com/42701133/100635673-241c7600-3374-11eb-93bc-978a47bcb16a.png)
  ![image](https://user-images.githubusercontent.com/42701133/100635710-2c74b100-3374-11eb-9e00-576034cd6f1a.png)
  </details>

  <details>
  <summary>Error catching의 안좋은 예 - 모든 에러를 한 번에 잡기</summary>

  ![image](https://user-images.githubusercontent.com/42701133/100635748-3ac2cd00-3374-11eb-9a7e-b9a6b35663df.png)
  </details>

# 04. 회원가입 뷰를 호출할 url을 작성해주세요

### ✅ 적절한 `url` 작성
> `view`를 잘 작성하셨다면, 이에 걸맞는 좋은 `url`을 붙여주는 것 까지가 좋은 엔드포인트를 생성하는 과정입니다. 작성한 함수에 적절하며, 그 의미에 맞는 `url`을 생성하셔야 합니다.

- **📍 관련 PR & Review**

  <details>
  <summary>url이 명확하지 않은 경우</summary>

  ![image](https://user-images.githubusercontent.com/42701133/100635905-6f368900-3374-11eb-8cf5-86019801ebb6.png)
  </details>

  <details>
  <summary> 슬래시(/)를 알맞게 붙이지 않은 경우</summary>

  ![image](https://user-images.githubusercontent.com/42701133/100630108-7b6b1800-336d-11eb-8ae6-94af673427b1.png)
  
  🛎 `REST_API` 에 대해 공부해보세요
  </details>

# 회원가입 과정을 확인해주세요
- httpie를 이용하여 서로 다른 10개의 계정을 회원가입 시켜주세요.

2021-05-02 07:09 UTC, Kang-kyunghun commented
- conflict 해결해 주세요.
- PR template 대신에 미션 내용이 올라와 있습니다. 확인하고 PR template 작성해 주세요.

2021-05-03 07:52 UTC, Kang-kyunghun requested changes

2021-05-03 07:52 UTC, Kang-kyunghun commented on students/unsan-Jeong/.gitignore
> +>>>>>>> feature/unsan-user-signup
이 부분 제거해 주세요.

2021-05-03 07:52 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/models.py
>  # Create your models here.
불필요한 주석 제거해 주세요.

2021-05-03 07:52 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/models.py
> +    update_at = models.DateTimeField(auto_now =True)
- 장고에서 id는 자동으로 지정 해주는데, 혹시 따로 선언한 이유가 있나요?
- 가독성을 위해 그리고 위코드 코드 컨벤션을 지키기 위해 =을 기준으로 정렬해 주세요.
- verbose_name을 사용한 이유와 용도를 코멘트로 남겨주세요.
- 전체적으로 최대 길이를 너무 빡빡하게 잡았습니다. 조금은 여유롭게 잡아 주세요.

2021-05-03 07:52 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/urls.py
> +    path('', SignUp.as_view()),
```suggestion
    path('/siginup', SignUp.as_view()),
```
다음과 같이 url을 설정하면 이 api가 어떤 기능을 하는지 바로 알 수 있습니다.

2021-05-03 07:52 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/views.py
> +                )
위코드 컨벤션에 맞춰주세요.

2021-05-03 07:52 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/views.py
> +            if len(data['password']) < 8:
비밀번호 길이가 8보다 작을 때 조건을 잘 만드셨습니다.
그런데, 나중에 기획이 바뀌어서 길이가 10보다 작을 때로 바뀌면 숫자 부분을 바꿔야 합니다. 지금은 1부분에서만 사용 했기 때문에 쉽게 바꿀 수 있지만, 나중에 프로젝트가 커지고 저러한 부분이 많이 사용 되었다면, 한 번 수정 할 때 어려움이 있습니다. 그래서 이럴 경우에는 상수를 하나 만들어서 거기에 데이터를 저장해서 사용합니다.

2021-05-03 07:52 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/views.py
> +                return JsonResponse({'MESSAGE':'email already exists'}, status=400)
```suggestion
            if (re.match('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', data['email']) == None):
                return JsonResponse({'MESSAGE':'Invalid email'}, status=400)
                
            if Users.objects.filter(name=data['name']).exists():
                return JsonResponse({'MESSAGE':'Name already exists'}, status=400)
                
            if Users.objects.filter(phone_number=data['phone_number']).exists():
                return JsonResponse({'MESSAGE':'Phone_number already exists'}, status=400)
                
            if Users.objects.filter(email=data['email']).exists():
                return JsonResponse({'MESSAGE':'email already exists'}, status=400)
                
```
이게 조금 더 가독성 있지 않을까요?

2021-05-03 08:38 UTC, Action2theFuture commented on students/unsan-Jeong/users/models.py
> +    update_at = models.DateTimeField(auto_now =True)
장고에서 id는 자동으로 지정 해주는데, 혹시 따로 선언한 이유가 있나요?
>>>auto-incrementing primary key를 사용하기 위해서 autofield를 사용했습니다
verbose_name을 사용한 이유와 용도를 코멘트로 남겨주세요.
>>>verbbose_name을 이용하여 키워드 인수로 사용할 수 있어서 프론트쪽으로 데이터를 받을 때 template에서 해당 인수를 통해 이름을 나타낼 수 있으므로 사용했습니다

2021-05-03 09:33 UTC, Kang-kyunghun requested changes

2021-05-03 09:33 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/models.py
> +    id           = models.BigAutoField(primary_key= True)
id를 지정해 주지 않아도 auto-increament로 적용 되는 걸로 알고 있습니다. 만약 그렇다면 필요 없지 않을까요?

2021-05-03 09:33 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/models.py
> +    email        = models.EmailField(max_length=128, verbose_name="user e-mail")
verbose_name을 template에서 사용하기 위해 적용 했다고 했는데, 저희는 template을 사용하지 않습니다.

2021-05-03 13:24 UTC, Kang-kyunghun requested changes
운산님 아무래도 merge 잘 못 된거 한 번 고치고 가야 할 것 같아요. 내일 한 번 같이 고쳐 보겠습니다.

2021-05-03 13:24 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/views.py
> +        password_length = 8
파이썬에서 상수는 대문자로만 이루어져 있습니다.
```suggestion
        PASSWORD_LENGTH = 8
```

2021-05-03 13:24 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/views.py
> +            if (re.match('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', data['email']) == None):
```suggestion
            if (re.match('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', data['email']) is None):
```
None을 비교 할 때는 is를 더 많이 사용합니다.

2021-05-06 08:32 UTC, closed without merging