[20기 정운산] 로그인 엔드포인트
wecode-bootcamp-korea/20-Westagram-backend pull request #17
Opened 2021-05-01 07:32 UTC by Action2theFuture

> ✔️ 우리 서비스의 회원으로 등록된 사용자를 로그인하도록 허가하는 과정에 대해 진행하겠습니다.

# 로그인 뷰 를 작성해주세요

- users 또는 accounts app 안에 로그인 view를 작성해주세요.
- 인스타그램에 회원가입 할 때에는 사용자 계정으로 **email**을 필수로 필요합니다.
- 인스타그램에 로그인 할 때에는 **비밀번호**가 필수로 필요합니다.
- 계정이나 패스워드 키가 전달되지 않았을 시, {"message": "KEY_ERROR"}, status code 400 을 반환합니다.
- 계정 잘 못 입력시 {"message": "INVALID_USER"}, status code 401을 반환합니다.
- 비밀번호 잘 못 입력시 {"message": "INVALID_USER"}, status code 401을 반환합니다.
- 로그인이 성공하면 {"message": "SUCCESS"}, status code 200을 반환합니다.

# 로그인 뷰를 호출할 url을 작성해주세요

# 로그인 과정을 확인해주세요
- httpie를 이용하여 로그인을 진행해보세요.
- 어떠한 잘못된 접근을 시도하였을 때, 어떤 에러가 나는지 블로깅해주세요.

2021-05-05 09:50 UTC, Kang-kyunghun requested changes

2021-05-05 09:50 UTC, Kang-kyunghun commented on students/unsan-Jeong/.gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/python,pycharm,vscode,vim,macos,linux,zsh
불필요한 부분입니다.

2021-05-05 09:50 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/views.py
> +        #     return JsonResponse({"MESSAGE": "INVALID_USER"}, status=401)
불필요한 코드는 PR에 포함시키지 말아주세요.

2021-05-05 09:50 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/views.py
> +    def get(self, request):
```suggestion
            return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=400)
            
    def get(self, request):
```

2021-05-05 09:50 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/views.py
> +            users = Users.objects.all()
```suggestion
        try:
            users = Users.objects.all()
```

2021-05-05 09:50 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/views.py
> +                    return JsonResponse({"message": "INVALID_USER"}, status=401)
로그인을 진행하는데 모든 유저를 불러와서 비교한 이유가 있을까요? 보통 로그인은 한 사람이 진행하기 때문에 프론트에서 받은 1명의 유저정보를 비교하는 로직으로 바꿔주세요.

2021-05-05 10:59 UTC, Kang-kyunghun requested changes

2021-05-05 10:59 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status=401)
```suggestion
            if not Users.objects.fliter(email=data['email']).exists():
                return JsonResponse({"message": "INVALID_USER"}, status=401)
```
.exists()의 결과가 이미 boolean이기 때문에 위와 같이 구성하는 것이 좋습니다.

2021-05-05 10:59 UTC, Kang-kyunghun commented on students/unsan-Jeong/users/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status=401)
암호화랑 token 발급도 한 번 추가해 보세요~

2021-05-05 13:05 UTC, Action2theFuture commented on students/unsan-Jeong/users/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status=401)
넵 🙋‍♂️

2021-05-05 13:07 UTC, Action2theFuture commented on students/unsan-Jeong/users/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status=401)
앗 실수였네요 ;;😲

2021-05-06 13:38 UTC, Kang-kyunghun commented
LGTM!!

2021-05-06 13:38 UTC, merged