[20기 최대환] [Mission 2] 회원가입 엔드포인트
wecode-bootcamp-korea/20-Westagram-backend pull request #18
Opened 2021-05-01 07:37 UTC by Dae-Hwan

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
- 이메일, 비밀번호로호로 회원정보를 등록할 수 있음
- 실패시 400 에러 반환
- 성공시 200 OK 반환
- urls 연결

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-02 07:03 UTC, Dae-Hwan commented
정규표현식이랑 이메일 중복 오류 수정해서 다시올렸습니다!

2021-05-02 07:26 UTC, Dae-Hwan commented
정규표현식으로 바꾸는 과정에서 있었던 오류 수정해서 다시 올렸습니다!

2021-05-02 07:32 UTC, Kang-kyunghun requested changes

2021-05-02 07:32 UTC, Kang-kyunghun commented on students/dae-hwan/user/models.py
> +    password     = models.CharField(max_length=45)
나주에 비밀번호 암호화를 하게 되는데 그 때를 대비해서 최대 길이를 넉넉히 잡아주면 좋을 것 같아요!

2021-05-02 07:32 UTC, Kang-kyunghun commented on students/dae-hwan/user/urls.py
> +    path('/sign_up', SignUpView.as_view())
```suggestion
    path('/signup', SignUpView.as_view())
```
url에서는 '_'에 대신에 '-'으로 단어를 연결합니다. 그리고 signup 같은 경우 관용적으로 붙여서 사용합니다.

2021-05-02 07:32 UTC, Kang-kyunghun commented on students/dae-hwan/user/views.py
> +            min_password = 8
상수 처리 너무 잘 하셨어요!!! 한 가지만 수정하자면, python에서 상수는 모두 대문자로만 이루어져 있도록 합니다.

2021-05-02 07:32 UTC, Kang-kyunghun commented on students/dae-hwan/user/views.py
> +            User.objects.create(
```suggestion
                return JsonResponse({'message': 'email exist'}, status = 400)
                
            User.objects.create(
```
공백을 한 칸 주는 것이 가독성에 더 좋을 것 같아요

2021-05-02 07:32 UTC, Kang-kyunghun commented on students/dae-hwan/user/views.py
> +                return JsonResponse({'message': 'email_validation'}, status = 400)
```suggestion
                return JsonResponse({'message': 'invalid email'}, status = 400)
```
위와 같은 메시지가 조금 더 어울릴 것 같아요. 그리고 메시지 형식은 통일하는 것이 좋습니다. 이 부분도 프론트랑 약속해야 하는 부분이기 때문입니다. 대문자로만 하겠다 또는 소문자에 '_'을 사용하겠다 등으로요
코드에 있는 에러 메시지들 한 번씩 다시 확인해 주세요.

2021-05-02 07:32 UTC, Kang-kyunghun commented on students/dae-hwan/user/views.py
> +                return JsonResponse({'message': 'nick_name exist'}, status = 400)
```suggestion
                return JsonResponse({'message': 'nick_name already exist'}, status = 400)
```
또는 
```suggestion
                return JsonResponse({'message': 'existing nick_name' }, status = 400)
```

2021-05-02 08:23 UTC, Dae-Hwan commented
피드백 한 부분 모두 수정 완료했습니다

2021-05-02 09:34 UTC, Kang-kyunghun requested changes

2021-05-02 09:34 UTC, Kang-kyunghun commented on students/dae-hwan/user/views.py
> +            email_validation    = re.compile( '^[a-z0-9]+@[a-z0-9]+\.[a-z0-9.]+$', re.I)
각각의 정규식이 무엇을 위한 건지 설명 부탁드립니다.

2021-05-02 23:31 UTC, Dae-Hwan commented
주석처리해서 정규식에 대한 설명을 덧붙였습니다.

2021-05-03 00:53 UTC, Dae-Hwan commented on students/dae-hwan/user/views.py
> +            email_validation    = re.compile( '^[a-z0-9]+@[a-z0-9]+\.[a-z0-9.]+$', re.I)
email_validation
^[a-z0-9]+     : 맨처음에 모든알파벳(뒤에 re.I를 붙여서 대문자도 포함)과 숫자가 한번씩 나오는 값을 의미한다.
@                 : @가 의무적으로 다음에 나와야된다느것을 의미한다.
[a-z0-9]+      : 그다음에는 모든 알파벳과 숫자가 한번씩나오는 값이 있어야 하고
\.                  : .만 쓰면 모든 문자열을 의미하기 때문에 \를 써서 특수문자.을 표현해 줬다.
[a-z0-9.]+$    : 맨마지막에 모든알파벳 또는 숫자, 또는 .이 하나이상 들어가야한다.

password_validation
.              : 모든 문자열
{%d,}      : 최소 % d번 이상 나와야된다( 최소한의 숫자를 문자열 포멧팅해서 넣었습니다)

2021-05-03 02:32 UTC, Dae-Hwan commented
log_in브랜치 삭제하고 다시올렸습니다!

2021-05-03 02:51 UTC, Kang-kyunghun requested changes

2021-05-03 02:51 UTC, Kang-kyunghun commented on students/dae-hwan/user/views.py
> +        # 정보가 잘 입력되었을 때
각 기능마다 주석을 넣어 주어 어떤 기능을 나타내는지 잘 보여주었습니다. 주석 같은 경우 사람마다 스타일이 다르기 때문에 보통 회사에서는 통일된 스타일로 가는 경우가 많습니다. 위코드에서는 조금 더 깔끔하고, 주석에 대한 오해를 방지하고자 깃허브에 올라오는 코드에는 주석을 제거하고 있습니다. 주석 부분 제거 부탁드리겠습니다.

2021-05-03 03:27 UTC, Dae-Hwan commented
주석 제거했습니다.

2021-05-03 07:53 UTC, Kang-kyunghun commented
고생 많으셨습니다~~!!

2021-05-03 07:54 UTC, merged