Feature/wooseok user app
wecode-bootcamp-korea/20-Westagram-backend pull request #22
Opened 2021-05-02 12:30 UTC by tonic523

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
-회원가입 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일, 비밀번호, 헨드폰 번호, 닉네임으로 회원가입
- 이메일 또는 패스워드 실패시 에러 반환
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 에러 처리를 try catch가 아닌 if절로 사용해도 되나요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.

2021-05-02 12:37 UTC, Kang-kyunghun commented
PR 제목 수정해 주세요.

2021-05-03 03:57 UTC, Kang-kyunghun requested changes

2021-05-03 03:57 UTC, Kang-kyunghun commented on students/wooseok-choi/user/urls.py
> +    path('/users', UserView.as_view()),
현재 url 조합이 어떻게 될까요?

2021-05-03 03:57 UTC, Kang-kyunghun commented on students/wooseok-choi/user/views.py
> +    return bool(match)
- print 제거해 주세요.
- 다음과 같은 코드는 utils 같은 파일을 만들어 따로 관리하는 것이 좋습니다~

2021-05-03 03:57 UTC, Kang-kyunghun commented on students/wooseok-choi/user/views.py
> +            data['nickname']
어떤 의도의 코드인지 코멘트 남겨주세요.

2021-05-03 03:57 UTC, Kang-kyunghun commented on students/wooseok-choi/user/views.py
> +            elif not validate_password(data['password']):
if문이 동작하게 되면 return이 되어 함수가 끝나게 되는데, 그러면 아래 elif로 굳이 체인닝 하지 않고, if으로 가능하지 않을까요? 하는 일비슷하지만, 가독성이 훨씬 증가 할 것 같습니다.

2021-05-03 03:57 UTC, Kang-kyunghun commented on students/wooseok-choi/user/views.py
> +            return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=400)
예외 처리는 가장 마지막으로 두어 코드 가독성을 증가 시킬 수 있습니다.

2021-05-03 03:57 UTC, Kang-kyunghun commented on students/wooseok-choi/user/views.py
> +                nickname = data['nickname']
=을 기준으로 정렬해 주세요.

2021-05-03 04:03 UTC, tonic523 commented on students/wooseok-choi/user/urls.py
> +    path('/users', UserView.as_view()),
user의 view에 접근하려면 127.0.0.1:8000/user/users 입니다!

2021-05-03 04:06 UTC, tonic523 commented on students/wooseok-choi/user/views.py
> +            data['nickname']
POST request 요청에 body에서 데이터 값이 하나라도 누락이 되면 KEY_ERROR로 response되기 위해 작성했어요

2021-05-03 04:07 UTC, tonic523 commented on students/wooseok-choi/user/views.py
> +            elif not validate_password(data['password']):
넵! 두 조건이 독립적이면 굳이 elif로 연결할 필요가 없는거군요

2021-05-03 04:11 UTC, tonic523 commented on students/wooseok-choi/user/views.py
> +            return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=400)
오 넵! try문에 User 클래스에 데이터를 추가하는 코드를 넣으면 위 26~29번 코드는 필요없을 것 같아요

2021-05-03 04:20 UTC, tonic523 commented on students/wooseok-choi/user/urls.py
> +    path('/users', UserView.as_view()),
url 접근을 회원가입으로 바꾸는 좋을까요? ex) /signup

2021-05-03 09:19 UTC, Kang-kyunghun requested changes

2021-05-03 09:19 UTC, Kang-kyunghun commented on students/wooseok-choi/user/models.py
>  # Create your models here.
불필요한 주석은 제거해 주세요.

2021-05-03 09:19 UTC, Kang-kyunghun commented on students/wooseok-choi/user/models.py
> +    nickname = models.CharField(max_length = 45)
- =을 기준으로 정렬해 주세요.
-이미 user라는 테이블의 email의 값을 넣어 주는 것이기 때문이 user_email 대신 email만으로도 충분합니다. password도 만찬가지 입니다.
- 각 field의 max_length가 전부 45인데, 각 속성에 맞게 설정해 주면 좋을 것 같아요.(너무 빡빡하지 않게 조금은 여유를 줘서)

2021-05-03 09:19 UTC, Kang-kyunghun commented on students/wooseok-choi/user/urls.py
> +    path('/users', UserView.as_view()),
/siginup이 가장 일반으로 사용됩니다~~

2021-05-03 09:19 UTC, Kang-kyunghun commented on students/wooseok-choi/user/views.py
> +    return bool(match)
파일을 따로 빼서 관리하는 것이 좋습니다.

2021-05-03 09:19 UTC, Kang-kyunghun commented on students/wooseok-choi/user/views.py
> +
email 중복 여부에 대한 예외 상황도 추가해 주세요.

2021-05-03 09:19 UTC, Kang-kyunghun commented on students/wooseok-choi/user/views.py
> +            return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=400)
가장 밑으로 내려 가독성을 높여 주세요.

2021-05-03 11:08 UTC, tonic523 commented on students/wooseok-choi/user/views.py
> +    return bool(match)
validate.py 를 user app 안에 추가했습니다.

2021-05-03 13:50 UTC, Kang-kyunghun requested changes

2021-05-03 13:50 UTC, Kang-kyunghun commented on students/wooseok-choi/user/models.py
> +    nickname     = models.CharField(max_length = 40)
max_length가 너무 빡빡합니다. 조금 여유롭게 두는 것이 좋습니다. 그리고 비밀번호는 암호화 진행하게 되는 훨씬 길어집니다.

2021-05-03 13:50 UTC, Kang-kyunghun commented on students/wooseok-choi/user/validate.py
> +        return True
좋지 못 한 방법이라고 생각 됩니다. 일단 get을 통한 except를 명확하게 하지 않아 디버깅에 어려움이 있으며, 굳이 함수를 따로 관리하면서 try까지 사용하는 것은 살짝 투머치로 보입니다.

2021-05-03 13:50 UTC, Kang-kyunghun commented on students/wooseok-choi/user/views.py
> +                return JsonResponse({'message':'DUPLICATE EMAIL'}, status=409)
```suggestion
            if User.objects.filter(email=data['email'].exists:
                return JsonResponse({'message':'DUPLICATE EMAIL'}, status=409)
```
해당 방법을 추천 드립니다. 왜 이 방법이 더 좋을까 한 번 생각해 보시면 좋을 것 같아요

2021-05-03 13:50 UTC, Kang-kyunghun commented on students/wooseok-choi/user/views.py
> +from user.validate import *
```suggestion
from user.validate import 
```
실제 코드에서 *을 사용하는 것은 좋지 못한 습관입니다. 사용할 모듈 또는 함수를 명확히 하는 것이 좋습니다.

2021-05-04 02:35 UTC, tonic523 commented on students/wooseok-choi/user/views.py
> +                return JsonResponse({'message':'DUPLICATE EMAIL'}, status=409)
제가 처음에 작성한 try문은 email이 존재 유무 뿐만 아니라 다른 에러들도 예외처리가 나와서 명확하지 않은 함수였던 것 같아요
또 함수에 try문을 넣고 그 함수를 import 하는 것은 비효율적인 것 같습니다. 쿼리셋의 exists 메소드를 사용하는 것이 훨씬 명확하고 간결한 코드인 것 같아요!

2021-05-04 03:05 UTC, Kang-kyunghun requested changes

2021-05-04 03:05 UTC, Kang-kyunghun commented on students/wooseok-choi/user/views.py
> +
공백은 1칸으로 해주세요.

2021-05-04 03:05 UTC, Kang-kyunghun commented on students/wooseok-choi/user/views.py
> +                return JsonResponse({'message':'DUPLICATE EMAIL'}, status=409)
```suggestion
            if not validate_email(data['email']):
                return JsonResponse({'message':'INVALID EMAIL'}, status=400)
                
            if not validate_password(data['password']):
                return JsonResponse({'message':'INVALID PASSWORD'}, status=400)
                 
            if User.objects.filter(email = data['email']).exists():
                return JsonResponse({'message':'DUPLICATE EMAIL'}, status=409)
```
가독성 측면에서 다음과 같이 공백을 추가하면 좋을 것 같습니다.

2021-05-04 03:05 UTC, Kang-kyunghun commented on students/wooseok-choi/user/models.py
> +
불피요한 공백은 제거해 주세요.

2021-05-04 03:05 UTC, Kang-kyunghun commented on students/wooseok-choi/user/validate.py
> +
불피요한 공백은 제거해 주세요.

2021-05-04 05:37 UTC, tonic523 commented on students/wooseok-choi/user/views.py
> +                return JsonResponse({'message':'DUPLICATE EMAIL'}, status=409)
넵!

2021-05-04 10:52 UTC, Kang-kyunghun commented
LGTM~~!!!

2021-05-04 10:52 UTC, merged