[20기 최대환] [Mission 3] 로그인 엔드포인트
wecode-bootcamp-korea/20-Westagram-backend pull request #27
Opened 2021-05-03 03:22 UTC by Dae-Hwan

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
- 이메일과 비밀번호를 활용해 로그인 가능
- 실패시 401에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- models.py 에서는 저 두개의 속성밖에 안쓰일거 같아서 저렇게만 넣었는데 괜찮을까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-04 10:53 UTC, Kang-kyunghun commented
conflict 해결해 주세요.

2021-05-04 11:48 UTC, Dae-Hwan commented
conflict문제 해결했습니다!

2021-05-05 08:44 UTC, Kang-kyunghun requested changes

2021-05-05 08:44 UTC, Kang-kyunghun commented on students/dae-hwan/user/views.py
> +
대환님 로그인 기능 잘 만드셨습니다. 그래서 추가적으로 bcrypt을 이용하여 비밀번호 암호화 후 token 발급까지 진행해 보시면 좋을 것 같습니다.~

2021-05-05 09:19 UTC, Dae-Hwan commented on students/dae-hwan/user/views.py
> +
token 발급까지 완료했습니다

2021-05-05 09:53 UTC, Kang-kyunghun requested changes

2021-05-05 09:53 UTC, Kang-kyunghun commented on students/dae-hwan/user/views.py
> +        return HttpResponse(status = 403)
token 발급은 로그인 과정에 통합 되어 있어야 합니다.

2021-05-05 12:13 UTC, Dae-Hwan commented on students/dae-hwan/user/views.py
> +        return HttpResponse(status = 403)
통합했습니다!
postings 앱에 view들을 데코레이터로 사용 권한을 부여하고 있는 중인데, 그건 너무 어려워서 일단 로그인과정에서 토큰이 발급되는거까지만 하고 제출합니다..

2021-05-05 15:11 UTC, Kang-kyunghun commented
고생 하셨습니다~~!!

2021-05-05 15:11 UTC, merged