[20기 김경래] Mission 2 회원가입 엔드포인트
wecode-bootcamp-korea/20-Westagram-backend pull request #33
Opened 2021-05-03 08:38 UTC by kyeongraekim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-03 09:39 UTC, Kang-kyunghun requested changes

2021-05-03 09:39 UTC, Kang-kyunghun commented on students/kyeongrae-kim/user/models.py
> +    modified_at = models.DateField(auto_now=True)
위코드 코드 컨벤션에 맞춰주세요.

2021-05-03 09:39 UTC, Kang-kyunghun commented on students/kyeongrae-kim/user/urls.py
> +    path('', UserView.as_view()),
회원가입 view을 실행하기 위한 url 조합이 어떻게 되나요?

2021-05-03 09:39 UTC, Kang-kyunghun commented on students/kyeongrae-kim/user/views.py
> +                return JsonResponse({'SIGNUP':'BAD_REQUEST_KEY_ERROR'}, status=400)
```suggestion
                return JsonResponse({'MESSAGE':'KEY_ERROR'}, status=400)
```
키를 통일 시킨 것은 잘 하셨습니다. 이미 내가 요청한 곳을 알기 때문에 어떤 기능에서 난 에러인지 명시 안 하셔도 되며, 같은 에러여도 기능마다 key가 달라지게 됩니다. 그리고 이미 400으로 bad request인 것까지는 알기 때문에 bad request도 없어도 될 것 같습니다.

2021-05-03 09:39 UTC, Kang-kyunghun commented on students/kyeongrae-kim/user/views.py
> +            else:
논리상 else가 필요할까 한 번 생각해 보세요. elif랑 같은 맥락입니다.

2021-05-03 09:39 UTC, Kang-kyunghun commented on students/kyeongrae-kim/user/views.py
> +            return JsonResponse({'SIGNUP':'BAD_REQUEST_KEY_ERROR'}, status=400)
가장 밑으로 내려 가독성을 높여 주세요.

2021-05-03 09:39 UTC, Kang-kyunghun commented on students/kyeongrae-kim/user/views.py
> +            return JsonResponse({'SIGNUP':'SUCCESS'}, status=201)
이 부분도 except가 내려왔을 때 else가 반든시 필요한지 생각해 보세요.

2021-05-03 10:20 UTC, kyeongraekim commented on students/kyeongrae-kim/user/models.py
> +    modified_at = models.DateField(auto_now=True)
위코드 컨벤션에 맞게 수정하였습니다.

2021-05-03 10:21 UTC, kyeongraekim commented on students/kyeongrae-kim/user/views.py
> +                return JsonResponse({'SIGNUP':'BAD_REQUEST_KEY_ERROR'}, status=400)
메세지의 불필요한 중복을 줄이고 정확한 의미 전달을 위해 미사여구를 줄였습니다.

2021-05-03 10:24 UTC, kyeongraekim commented on students/kyeongrae-kim/user/views.py
> +            else:
올바른 사용자 입력정보들이 에러유발 조건을 피해 if 문들을 다 훑고 내려오게되면,
논리구조상 자연스럽게 else문이 불필요해집니다. 따라서 삭제 완료하였습니다.

2021-05-03 10:24 UTC, kyeongraekim commented on students/kyeongrae-kim/user/views.py
> +            return JsonResponse({'SIGNUP':'BAD_REQUEST_KEY_ERROR'}, status=400)
해당 문장, 가장 밑으로 내려서 수정하였습니다.

2021-05-03 10:27 UTC, kyeongraekim commented on students/kyeongrae-kim/user/views.py
> +            return JsonResponse({'SIGNUP':'SUCCESS'}, status=201)
올바른 사용자 입력정보들이 에러유발 조건을 피해 if 문들을 다 훑고 내려오게되면,
논리구조상 자연스럽게 else문이 불필요해집니다.
이에 따라 불필요한 조건문을 삭제 완료하였습니다.
그 동안 try, except, else, finally로 이어지는 문법적 사고 프레임에 갇혀서, 
꼭 사용해야한다는 강박관념이 있었던 것 같습니다.

2021-05-03 10:49 UTC, kyeongraekim commented on students/kyeongrae-kim/user/urls.py
> +    path('', UserView.as_view()),
user로만 적혀있어서 의미가 불명확했던 기존 커밋 내  url path를,
1) views.py 내 post 함수 Class명 변경(SignUpView),
2) 상위 urls.py 내 'user' path 경로 지정,
3) 하위 urls.py 내 '/signup' path 경로 지정을 함으로써,

내부 도메인을 "user/signup" 으로 변경하였고, 
회원가입 기능의 정상작동을 확인함.

2021-05-03 13:35 UTC, Kang-kyunghun requested changes

2021-05-03 13:35 UTC, Kang-kyunghun commented on students/kyeongrae-kim/user/models.py
> +    modified_at     = models.DateField(auto_now=True)
create_at은 datetime을 사용했는데, 왜 modified는 date인가요?(궁금)
그리고 관용적으로 update_at을 더 사용하는 편입니다.

2021-05-03 13:35 UTC, Kang-kyunghun commented on students/kyeongrae-kim/user/views.py
> +        regex = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'
- =을 기준으로 정렬해 주세요.
- 해당 정규 표현식이 어떠한 역할을 하는지 코멘트로 설명 남겨 주세요.
- User.objects이 반복 되기 때문에 변수에 담은 것 같은데, 오히려 의미를 퇴색 시키는 것 같습니다.

2021-05-03 13:35 UTC, Kang-kyunghun commented on students/kyeongrae-kim/user/views.py
> +            if len(data['password']) < 8:
비밀번호 길이가 8보다 작을 때 조건을 잘 만드셨습니다.
그런데, 나중에 기획이 바뀌어서 길이가 10보다 작을 때로 바뀌면 숫자 부분을 바꿔야 합니다. 지금은 1부분에서만 사용 했기 때문에 쉽게 바꿀 수 있지만, 나중에 프로젝트가 커지고 저러한 부분이 많이 사용 되었다면, 한 번 수정 할 때 어려움이 있습니다. 그래서 이럴 경우에는 상수를 하나 만들어서 거기에 데이터를 저장해서 사용합니다.

2021-05-03 13:35 UTC, Kang-kyunghun commented on students/kyeongrae-kim/user/views.py
> +
```suggestion
                return JsonResponse({'MESSAGE':'PASSWORD_KEY_ERROR'}, status=400)
                
            if users_info.filter(email=data['email']):                  
                return JsonResponse({'MESSAGE':'USER_ALREADY_EXISTS'}, status=400)
                
            if users_info.filter(username=data['username']):           
                return JsonResponse({'MESSAGE':'USER_ALREADY_EXISTS'}, status=400)
                
            if users_info.filter(mobile_num=data['mobile_num']):       
                return JsonResponse({'MESSAGE':'USER_ALREADY_EXISTS'}, status=400)   
                
            user = User.objects.create(                            
                email           = data['email'],
                password        = data['password'],
                mobile_num      = data['mobile_num'],
                username        = data['username'],
            )
            return JsonResponse({'MESSAGE':'SUCCESS'}, status=201)

```
가독성 측면에서 다음과 같이 수정하면 좋을 것 같습니다.

2021-05-03 14:44 UTC, kyeongraekim commented on students/kyeongrae-kim/user/models.py
> +    modified_at     = models.DateField(auto_now=True)
- DateTimeField를 의도하였는데 작성 중 오타가 난 것 같습니다. 수정하였습니다.
- modified_at 을 update_at으로 변경완료 하였습니다. 통상적으로 흔히 쓰는 영문 표기을 더 익히도록 하겠습니다.

2021-05-03 15:01 UTC, kyeongraekim commented on students/kyeongrae-kim/user/views.py
> +        regex = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'
- 위코드 컨벤션을 따라 '=' 위치를 통일하였습니다.
  말씀해주신 내용에 공감하여 , 
-아무리 반복되어도 치환된 후의 변수명이 효율성면에서 효과가 미비하고,
  본래의 의미를 덜 담아낸다면, 앞으로 사용을 지양하겠습니다.

- 해당 정규표현식의 구체적은 기능은 아래와 같습니다:
1) ^는 문자열의 시작 부분을 매칭합니다. 여기서는 ^ 이후로 오는 이메일의 유효성을 판단한다는 의미를 내포하고 있습니다.
2) [a-z0-9] 은 소문자 알파벳 a부터 z와 0에서9까지의 숫자로 해당 이메일이 이루어졌는지 검증합니다.
3) [\._]?은 이메일상 온점 . 이 한 번 이상 반복되는 지를 검증합니다. 이메일에서는 점이 2번이상 오면 안되기에 이를 잡아내기 위함입니다.
4) 위 2번내용과 동일합니다.
5) [@]는 골뱅이 표시를 찾아내는 기능을 합니다. 그 직후 오는 \w 는 알파벳+숫자로 이루어진 글자를 매칭합니다.
6) [.]/w{2,3} 은 알파벳 + 숫자로 이루어진 2~3자의 글자가 온점 뒤에 오는지 검사합니다. 
7) $는 유효성 검증을 위한 문자열이 끝나는 지점을 의미합니다.

2021-05-03 15:02 UTC, kyeongraekim commented on students/kyeongrae-kim/user/views.py
> +            if len(data['password']) < 8:
향후 상수 설정의 여지를 두기 위해 PASSWORD = 8 로,
상수 변수 네이밍 컨벤션을 따라 코드를 작성하였습니다.

2021-05-03 15:04 UTC, kyeongraekim commented on students/kyeongrae-kim/user/views.py
> +
가독성 향상을 위해 필요한 곳에 라인 브레이킹을 하였습니다.

2021-05-04 02:07 UTC, Kang-kyunghun commented
LGTM~~~!!!

2021-05-04 02:07 UTC, merged