[20기 최우석] Mission 3 로그인 엔드포인트
wecode-bootcamp-korea/20-Westagram-backend pull request #34
Opened 2021-05-03 08:56 UTC by tonic523

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 로그인 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
- 이메일과 비밀번호로 로그인 시도
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
except 오류의 이름을 실행하면서 알 수 있는 방법이 있나요?
알게 되면 except: 말고 except 오류이름: 으로 사용하고 싶어요

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.

2021-05-04 11:09 UTC, Kang-kyunghun commented
conflict 해결해 주세요.

2021-05-05 01:56 UTC, tonic523 commented
conflict 해결했습니다!

2021-05-05 09:09 UTC, Kang-kyunghun requested changes

2021-05-05 09:09 UTC, Kang-kyunghun commented on students/wooseok-choi/user/validate.py
> +    regex = re.compile('^[a-z0-9_-]{8,}$', re.I)
비밀번호 길이가 8보다 작을 때 조건을 잘 만드셨습니다.
그런데, 나중에 기획이 바뀌어서 길이가 10보다 작을 때로 바뀌면 숫자 부분을 바꿔야 합니다. 지금은 1부분에서만 사용 했기 때문에 쉽게 바꿀 수 있지만, 나중에 프로젝트가 커지고 저러한 부분이 많이 사용 되었다면, 한 번 수정 할 때 어려움이 있습니다. 그래서 이럴 경우에는 상수를 하나 만들어서 거기에 데이터를 저장해서 사용합니다.

2021-05-05 09:09 UTC, Kang-kyunghun commented on students/wooseok-choi/user/views.py
> +        return JsonResponse({"message":"SUCCESS"}, status=200)
로그인 구현 잘 하셨습니다. 추가적으로 bycrpt로 비밀번호 암호화 하는 과정과 token 발급까지 구현해 보세요

2021-05-06 13:40 UTC, Kang-kyunghun commented
LGTM~~!!

2021-05-06 13:41 UTC, merged