[20기 김하민] Mission 2 회원가입 엔드포인트
wecode-bootcamp-korea/20-Westagram-backend pull request #36
Opened 2021-05-03 12:10 UTC by HaMin-Kim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 API 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원가입 models.py 작성
- 회원가입 view 작성
- url 엔드포인트

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-03 13:28 UTC, Kang-kyunghun requested changes

2021-05-03 13:28 UTC, Kang-kyunghun commented on students/hamin-Kim/user/views.py
> +
불필요한 공백입니다.

2021-05-03 13:28 UTC, Kang-kyunghun commented on students/hamin-Kim/user/views.py
> +                    or Users.objects.filter(phonenumber = data["phonenumber"]):
처음에는 .exists을 사용 했는데, 이 부분에서 안 사용한 이유가 있을까요?

2021-05-03 13:28 UTC, Kang-kyunghun commented on students/hamin-Kim/user/models.py
> +    password    = models.IntegerField()
password에는 숫자만 들어오지 않습니다. 적적한 field도 수정해 주세요.

2021-05-03 13:28 UTC, Kang-kyunghun commented on students/hamin-Kim/user/models.py
> +    phonenumber = models.IntegerField(unique=True, blank=True)
핸드폰 번호도 여러 가지 확장성을 고려하고 숫자로만 구성하지 않습니다.

2021-05-03 13:28 UTC, Kang-kyunghun commented on students/hamin-Kim/user/models.py
> +    update_date = models.DateField(auto_now=True)
일반적으로 시간을 기록할 때 시간까지 저장합니다.

2021-05-03 13:28 UTC, Kang-kyunghun commented on students/hamin-Kim/.idea/hamin-Kim.iml
> +</module>
파이참 때문에 생긴 불피요한 파일입니다. 이거 이외에도 몇개 더 있으니 제거히고 다시 push해 주세요.

2021-05-04 02:21 UTC, HaMin-Kim commented on students/hamin-Kim/.idea/hamin-Kim.iml
> +</module>
.idea 폴더 삭제하였습니다.

2021-05-04 02:22 UTC, HaMin-Kim commented on students/hamin-Kim/user/models.py
> +    update_date = models.DateField(auto_now=True)
수정하였습니다.

2021-05-04 02:22 UTC, HaMin-Kim commented on students/hamin-Kim/user/models.py
> +    phonenumber = models.IntegerField(unique=True, blank=True)
수정하였습니다.

2021-05-04 02:22 UTC, HaMin-Kim commented on students/hamin-Kim/user/models.py
> +    password    = models.IntegerField()
수정하였습니다.

2021-05-04 02:22 UTC, HaMin-Kim commented on students/hamin-Kim/user/views.py
> +                    or Users.objects.filter(phonenumber = data["phonenumber"]):
실수로 빼먹었습니다. 추가하였습니다.

2021-05-04 02:22 UTC, HaMin-Kim commented on students/hamin-Kim/user/views.py
> +
공백 제거하였습니다.

2021-05-04 02:51 UTC, Kang-kyunghun requested changes

2021-05-04 02:51 UTC, Kang-kyunghun commented on students/hamin-Kim/user/models.py
> +    phonenumber = models.CharField(max_length=20, blank=True)
max_length을 너무 빡빡하게 잡은 것 같습니다. 조금 여유롭게 잡으셔도 될 것 같습니다.

2021-05-04 02:52 UTC, Kang-kyunghun commented
로그인 코드에서 max_length 수정해 주세요.

2021-05-04 02:52 UTC, merged