[20기 양영건] Mission 2 회원가입 기능
wecode-bootcamp-korea/20-Westagram-backend pull request #44
Opened 2021-05-04 04:47 UTC by 111geon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
- email, password를 이용하여 회원가입할 수 있음(phone, nickname은 옵션)
- 이름 형식에 안맞거나 중복 데이터가 있으면 에러 반환
- 성공시 database에 입력하고 200 OK 반환

## 기타 질문 및 특이 사항
- 없습니다 코멘트 부탁 드립니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-04 04:49 UTC, 111geon commented
지금 보니 commit message를 잘못 작성하였습니다.
"로그인 기능 추가" -> "회원가입 기능 추가" 입니다.

2021-05-04 11:04 UTC, 111geon commented
말씀하신 수정사항 반영하였습니다.
뷰 코드가 훨씬 깔끔하게 느껴집니다.

2021-05-05 09:30 UTC, Kang-kyunghun requested changes

2021-05-05 09:30 UTC, Kang-kyunghun commented on students/younggeon-yang/user/errors.py
> +        super().__init__(EmailFormatError.error_message+whaterror)
excrption을 커스터 마이징 너무 잘 하셨습니다. 그런데, 해당 exception들을 프로젝트 전반적으로 공통되게 사용 되기에는 힘들어 보입니다. 그렇기 때문에 굳이 이렇게까지 만들지 않고 로직으로 충분히 커버할 수 있지 않을까 싶습니다. 이번 프로젝트에서는 제거해 주세요.
그래도 커스터마이징 하는 방법을 공부하고 적용한데 있어 의미가 있다고 생각 됩니다.

2021-05-05 09:30 UTC, Kang-kyunghun commented on students/younggeon-yang/user/urls.py
> +    path('/', UserView.as_view()),
```suggestion
    path('/signup', UserView.as_view()),
```
위와 같이 하는 것이 조금 더 명확하게 회원가입을 나타내지 않을까요~~?

2021-05-05 09:30 UTC, Kang-kyunghun commented on students/younggeon-yang/user/views.py
> +class UserView(View):
```suggestion
class SignUpView(View):
```
해당 뷰의 이름도 위와 같이 하는 것이 조금 더 명확할 것 같습니다.

2021-05-05 09:30 UTC, Kang-kyunghun commented on students/younggeon-yang/user/views.py
> +            # 전화번호, 닉네임이 있다면 저장하고 없다면 None 값 저장
각 기능마다 주석을 넣어 주어 어떤 기능을 나타내는지 잘 보여주었습니다. 주석 같은 경우 사람마다 스타일이 다르기 때문에 보통 회사에서는 통일된 스타일로 가는 경우가 많습니다. 위코드에서는 조금 더 깔끔하고, 주석에 대한 오해를 방지하고자 깃허브에 올라오는 코드에는 주석을 제거하고 있습니다. 주석 부분 제거 부탁드리겠습니다.

2021-05-05 09:30 UTC, Kang-kyunghun commented on students/younggeon-yang/user/validations.py
> +        return
validator와 exeption이 복잡하게 엮여 있어 오히려 가독성이 떨어지는 것 같습니다.

2021-05-05 09:30 UTC, Kang-kyunghun commented on students/younggeon-yang/user/views.py
> +        return JsonResponse({'message': 'SUCCESS'}, status=201)
성공 같은 경우 except보다 위에 존재하게 하여 가독성을 높일 수 있습니다.

2021-05-05 09:30 UTC, Kang-kyunghun commented on students/younggeon-yang/user/views.py
> +            Validation.validate_duplication(self, email, phone, nickname)
조건문과 validation 조합으로 조금 더 깔끔한 로직 구현이 가능 할 것 같은데 한 번 고민해 보세요.

2021-05-05 13:57 UTC, 111geon commented
리뷰하신 내용 반영하여 수정하였습니다!
- view class 이름 명확하게 변경
- url 명확하게 수정
- 주석 삭제
- exceptions 커스터마이징 삭제 후 간단한 로직으로 view 수정

2021-05-05 15:19 UTC, Kang-kyunghun requested changes

2021-05-05 15:19 UTC, Kang-kyunghun commented on students/younggeon-yang/user/views.py
> +            nickname = None if not nickname else nickname
이미 위에 정의 했는데, 다시 정의할 필요 없어 보입니다 이미 get 자체가 default 값을 가지기 때문입니다.

2021-05-05 15:19 UTC, Kang-kyunghun commented on students/younggeon-yang/user/views.py
> +
```suggestion
            if not Validation.validate_email(self, email):
                return JsonResponse({'message': 'Error email'}, status=400)
                
            if not Validation.validate_password(self, password):
                return JsonResponse({'message': 'Error password'}, status=400)
                
            if not Validation.validate_duplication(self, email, phone, nickname):
                return JsonResponse({'message': 'Already exist'}, status=400)

```
이렇게 하면 가독성을 높일 수 있습니다.

2021-05-05 23:29 UTC, 111geon commented on students/younggeon-yang/user/views.py
> +            nickname = None if not nickname else nickname
이 부분은 phone 또는 nickname으로 빈 string ""이 들어간 경우 Database 상에 Null이 아닌 빈 string ""으로 데이터가 들어가는 것을 막기 위해 작성한 줄입니다!

2021-05-05 23:30 UTC, 111geon commented on students/younggeon-yang/user/views.py
> +
반영하였습니다!

2021-05-05 23:38 UTC, 111geon commented
코멘트 사항 반영하였습니다 확인 부탁 드립니다

2021-05-06 13:44 UTC, Kang-kyunghun commented on students/younggeon-yang/user/views.py
> +            nickname = None if not nickname else nickname
개인적으로 이 부분은 조건문으로 할 수 있지 않을까 생각이 들지만, merge 진행 하겠습니다~

2021-05-06 13:44 UTC, Kang-kyunghun commented
고생 하셨습니다.

2021-05-06 13:44 UTC, merged