[20기 문성호][MISSION2] 회원가입 end point
wecode-bootcamp-korea/20-Westagram-backend pull request #57
Opened 2021-05-05 06:04 UTC by Room9

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 end point 구현 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 닉네임과 폰번호는 필수 사항 아님
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 1차로 pr 리뷰 해주신 건은 commit이 꼬여서 push 되지 않아 삭제 후 재 pr 요청드렸습니다
- migrate 한 model 내 class의 이름을 바꿀 시 data가 모두 소실되던데 다른 방법이 있을까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-05 09:05 UTC, Kang-kyunghun requested changes

2021-05-05 09:05 UTC, Kang-kyunghun commented on students/sungho-moon/user/urls.py
> +from user.views import UserView
위코드 코드 컨벤션에 맞춰주세요.
```suggestion
from django.urls import path

from user.views  import UserView
```

2021-05-05 09:05 UTC, Kang-kyunghun commented on students/sungho-moon/user/views.py
> +        data_phonenumber = data.get('phonenumber')
=을 기준으로 정려해 주세요.

2021-05-05 09:05 UTC, Kang-kyunghun commented on students/sungho-moon/user/models.py
> +class USER(models.Model):
class 이름은 카멜케이스가 적용됩니다.
```suggestion
class User(models.Model):
```

2021-05-05 09:05 UTC, Kang-kyunghun commented on students/sungho-moon/westagram/urls.py
> +           path('westagram', include('user.urls'))
user와 관련된 app으로 연결 시켜주므로 아래와 같이 지정하는 것이 좋습니다.
```suggestion
           path('user', include('user.urls'))
```

2021-05-06 00:57 UTC, Room9 commented on students/sungho-moon/user/urls.py
> +from user.views import UserView
수정완료했습니다

2021-05-06 00:57 UTC, Room9 commented on students/sungho-moon/user/views.py
> +        data_phonenumber = data.get('phonenumber')
수정완료했습니다

2021-05-06 00:58 UTC, Room9 commented on students/sungho-moon/user/models.py
> +class USER(models.Model):
수정완료했습니다

2021-05-06 00:58 UTC, Room9 commented on students/sungho-moon/westagram/urls.py
> +           path('westagram', include('user.urls'))
수정완료했습니다

2021-05-06 13:46 UTC, Kang-kyunghun commented
고생 많으셨습니다.~!!

2021-05-06 13:47 UTC, merged