Feature/junsik initial setting
wecode-bootcamp-korea/20-Westagram-backend pull request #8
Opened 2021-04-30 08:26 UTC by JunsikChoi

## 수정 사항 간략한 한줄 요약
- Westagram Backend Project 초기 세팅
		 
## 수정 사항들 자세한 내용
1. CREATE: Django Project (d5ab11e)
2. MODIFY: settings.py (d0d3564)
3. CREATE: Users App (01aefe3) 
4. MODIFY: urls.py & views.py (08b0ed5)

## 체크 리스트 

- [v] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [v] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [v] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.

2021-04-30 15:13 UTC, Kang-kyunghun requested changes

2021-04-30 15:13 UTC, Kang-kyunghun commented on students/junsikchoi/westagram/settings.py
> +SECRET_KEY = 'django-insecure-@ugb89hhnh=2*l$)%gz008wsd*+#6o$ekku2nc=v@@z9exi++-'
my_settings로 옮겨주세요.

2021-04-30 15:13 UTC, Kang-kyunghun commented on students/junsikchoi/westagram/settings.py
> +}
my_settings로 옮기고 mysql로 셋팅 바꿔주세요.

2021-04-30 15:15 UTC, Kang-kyunghun commented
.gitignore와 my_settings.py도 추가해 주세요.

2021-05-02 09:07 UTC, JunsikChoi commented
수정사항 반영했습니다 :)

# ADD
- .gitignore
- README.md
- requirements.txt
- my_settings_sample.py

# Modify
- westagram/settings.py

2021-05-02 09:29 UTC, Kang-kyunghun requested changes

2021-05-02 09:29 UTC, Kang-kyunghun commented on students/junsikchoi/my_settings_sample.py
> +SECRET_KEY = "<Your Secret Key>"
불필요한 파일은 깃허브에 안 올라오게 해주세요.

2021-05-02 09:29 UTC, Kang-kyunghun commented on students/junsikchoi/westagram/settings.py
> +import my_settings as mySettings
python에서는 변수 명을 스네이크 케이스로 사용합니다.

2021-05-02 09:36 UTC, JunsikChoi commented on students/junsikchoi/westagram/settings.py
> +import my_settings as mySettings
수정했습니다.

2021-05-02 09:36 UTC, JunsikChoi commented on students/junsikchoi/my_settings_sample.py
> +SECRET_KEY = "<Your Secret Key>"
제거했습니다.

2021-05-03 02:37 UTC, Kang-kyunghun commented
LGTM~~!!

2021-05-03 02:37 UTC, merged